### ISSUE TITLE
error with @swc/core 1.3.51

### ISSUE THREAD

**Issue by xyhxx** [g-plane/swc-plugin-react-remove-properties#1]
[https://swc.rs/docs/plugin/selecting-swc-core](url)

v0.75.0
We enabled strict mode of rkyv and updated wasmer to v3.

@swc/core@1.3.49 ~

I'm not sure if it's related to this update, packaging will be interrupted when I use this plugin.

**Comment by g-plane** [comment]
We'll upgrade SWC.

**Comment by xyhxx** [comment]
that's great!
